#pragma once

const char DEV_NAME[] = "dev_name";
char devName[30] = {};
const char PARAM_CMD1[] = "cmd1";
const char PARAM3[] = "param3";
uint32_t Predkosc = 10;
int zmienna;
int zmienna1;
bool zmienna2 = false;
int jasnosc;
int jasnosc1; 
uint32_t redWSLED;
uint32_t greenWSLED;
uint32_t blueWSLED;
uint32_t redWSLED2;
uint32_t greenWSLED2;
uint32_t blueWSLED2;
const char SELECT_MODE[] = "select_mode";
uint32_t selectMode = 0;
const char TYP_TASMY[] = "tt";
uint32_t typ_tasmy = 0;
const char ILOSC_DIOD[] = "iloscdiod";
uint32_t ilosc_diod= 90;
const char BUTTON_STEP[] = "button_step";
int32_t btnStep = 1;
const char FADE_EFFECT[] = "fade_effect";
int32_t fadeEffect_ = 2000;
const char ITERATION_DELAY[] = "iteration_delay";
int32_t iterationDelay = 2000;
bool zapal_raz = false;
bool zgas_raz = false;
int regulacja = 0;
int licznik = 0;
unsigned long czasowka = 0;
bool tylko_raz = false;
bool trwa_animacja = false;
const char TYP_WLACZNIKA[] = "typ_wlacznika";
uint32_t Typ_Wlacznika = 0;